### ISSUE TITLE
I have a problem when I open the Safary explorer .

### ISSUE THREAD

**Issue by tocasoft** [traccar/traccar-client-ios#68]
Hello Anthon
I have a problem when I open the Safary explorer to show the window of the devices, reports and states. When I click on any of them, the tab does not open. you have some suggestion that you can help me. In windows it works well.
Thank you

**Comment by tananaev** [comment]
How is this related to Traccar Client?

**Comment by tocasoft** [comment]
Manager from web explorer in Safari.thanks

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 7, 2019 at 2:12 PM, Anton Tananaev<notifications@github.com> wrote:   
How is this related to Traccar Client?

**Comment by tananaev** [comment]
I'm closing this ticket because it clearly has nothing to do with Traccar Client app.

**Comment by tocasoft** [comment]
How i can fix this problem my friend or I must open  other ticket?.thanks

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 7, 2019 at 2:22 PM, Anton Tananaev<notifications@github.com> wrote:   
I'm closing this ticket because it clearly has nothing to do with Traccar Client app.

**Comment by tananaev** [comment]
You need to ask in appropriate place. If you think there is a bug in Traccar Manager, open ticket there. If you think it's web app issue, open ticket in web app repo.

**Comment by tocasoft** [comment]
Ok. Thanks

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 7, 2019 at 2:37 PM, Anton Tananaev<notifications@github.com> wrote:   
You need to ask in appropriate place. If you think there is a bug in Traccar Manager, open ticket there. If you think it's web app issue, open ticket in web app repo.
