### ISSUE TITLE
The project has compilation errors in the latest xcode14

### ISSUE THREAD

**Issue by gpsim** [traccar/traccar-client-ios#77]
**Describe the bug**
The project has compilation errors in the latest xcode14：
/traccar-client-ios/TraccarClient/AppDelegate.swift Could not build Objective-C module 'SwiftOverlayShims'

/traccar-client-ios/Pods/Firebase/CoreOnly/Sources/module.modulemap:1:8 Redefinition of module 'Firebase'

**To Reproduce**
1 Download the latest code through git

2. No changes have been made and cannot be compiled and run

**Expected behavior**
It may be a compatibility problem, but I don't know how to solve it. I hope you can help me analyze it. Thank you.

**Screenshots**
<img width="1072" alt="截屏2023-02-25 18 31 16" src="https://user-images.githubusercontent.com/6435368/221352209-4e91a380-c244-4913-b696-acd2fe1a47e3.png">

**Desktop (please complete the following information):**
- xcode Version 14.2 (14C18)
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS16.3]

**Comment by tananaev** [comment]
Are you sure you did a clean check of the latest code?

**Comment by gpsim** [comment]
My mac has two accounts. Just switch to another account. It's strange. I'm very sorry for the confusion. It has been solved at present.
