### ISSUE TITLE
Can't stay alive in background

### ISSUE THREAD

**Issue by bradley-rose** [traccar/traccar-client-ios#78]
**Describe the bug**
The app can't stay alive in the background. It stops logging points when not in the foreground. 

**To Reproduce**
1. Open app
2. Start logging
3. Swipe up to put app in background

**Expected behavior**
Log points to Traccar Server

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Mini
 - OS: 16.5

**Additional context**
There's no options for Background App Refresh for Traccar Client. It's just not listed in the list.

**Comment by tananaev** [comment]
Have you checked system logs to see what happens?

PS Background App Refresh is something unrelated, afaik. We request background location updates instead.

**Comment by bradley-rose** [comment]
> Have you checked system logs to see what happens?
> 
> 
> 
> PS Background App Refresh is something unrelated, afaik. We request background location updates instead.

Which system logs specifically? Somewhere in the iOS settings app that I should be looking?

**Comment by tananaev** [comment]
iOS system logs.

**Comment by bradley-rose** [comment]
There's no logs for Traccar Client. 

![image](https://github.com/traccar/traccar-client-ios/assets/91505167/6f93d1c8-0a36-427c-a2ae-4c9020cf4d86)

**Comment by tananaev** [comment]
What is this? Once again, I'm talking about system logs. There should be a single log, not per app log.

**Comment by bradley-rose** [comment]
Looks like the system log is only able to be accessed via desktop based on what I'm reading on a web search. I'll update later when I get around to investigating further.

**Comment by bradley-rose** [comment]
Seems to have fixed itself over time. No direct actions were taken. Tested in outdoor, indoor, moving, and static environments, all seems to just work.
