### ISSUE TITLE
Add Support for Apples new "Background App Refresh"

### ISSUE THREAD

**Issue by Neon-44** [traccar/traccar-client-ios#85]
**Is your feature request related to a problem? Please describe.**
I just can't get Traccar to reliably update the location from iOS (It always kills the process). 

**Describe the solution you'd like**
Adding Support for "Background App refresh" would allow the App to continue sending the Location even when it's killed in the foreground. 

**Describe alternatives you've considered**
nothing

**Additional context**
on iOS: Settings -> General -> Background App Refresh

**Comment by tananaev** [comment]
We already support background location, so I'm not exactly sure what the request is.

**Comment by Neon-44** [comment]
Huh, it doesn't show up in the settings for me.

A Bug Report then?

**Comment by tananaev** [comment]
Background Location Updates and Background App Refresh are two separate mechanisms in iOS.

**Comment by Neon-44** [comment]
so, if I close the app (swipe it up) and the process gets killed that's expected behaviour?

If yes, would it be possible to implement background app refresh so the process stays alive?

**Comment by tananaev** [comment]
If you explicitly kill the app (swipe it up), neither of those will work. If you want the app to keep running in the background, don't kill it.
